@startuml Loja
    class Produto {
        +String codigo_barras
        +String nome
        +Float preco

        +Void adicionaDados()
        +String toString()
        +Boolean __eq__()
    }

    class Livro{
        +String autor

        +Void adicionaDados()
        +String toString()
        
    }
    class CD {
        +Integer n_faixas

        +Void adicionaDados()
        +String toString()
        
    }
    class DVD{
        +Integer duracao

        +Void adicionaDados()
        +String toString()
    }   

    class Loja{
        +List banco_de_dados

        +Void MostrarProdutosCadastrados()
        +Void CadastrarProduto()
        +Integer busca_produto()
        +Void main()
    }

    Produto <|-- Livro
    Produto <|-- CD
    Produto <|-- DVD

@enduml